name: "Trigger Tag Event"
description: "Trigger tag event via workflow_dispatch as tagging with GITHUB_TOKEN prevent upcoming event from being triggered"
inputs:
  tag:
    description: "Tag for trigger"
    required: true
  workflow_id:
    description: 'Workflow that will be triggered'
    required: true
  github_tokengithub_token:
    description: "Github token for trigger workflow dispatch"
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Tag Event
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${inputs.workflow_id}',
              ref: `refs/tags/${inputs.tag}`,
              inputs: {
                tag: inputs.tag
              },
            })
            console.log(result);
          } catch(error) {
            console.error(error);
            core.setFailed(error);
          }
