name: "Trigger Tag Event"
description: "Trigger tag event via workflow_dispatch"
inputs:
  tag:
    description: "Tag for trigger"
    required: true
  workflow_id:
    description: "Workflow that will be triggered"
    required: true
  github_ssh_private_key:
    description: "SSH private key for read/write on git repository"
    required: true

runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.github_ssh_private_key }}

    - name: Trigger Tag Event
      uses: actions/github-script@v5
      with:
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ inputs.workflow_id }}',
              ref: `refs/tags/${{ inputs.tag }}`,
              inputs: {
                tag: `${{ inputs.tag }}`
              },
            })
            console.log(result);
          } catch(error) {
            console.error(error);
            core.setFailed(error);
          }
