name: "Get All Files Action"
description: "Retrieve the list of files that have changed between two specified git commit SHAs under a given path"
inputs:
  path:
    description: "The path to filter the diff files"
    required: true
  artifact_name:
    description: "The artifact key name for allow the caller to download with action"
    required: true
  file_name:
    description: "The output file name in artifact"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get All Files
      shell: bash
      run: |
        find "${{ inputs.path }}" -type f > ${{ inputs.file_name }}

    - name: Upload Diff Files Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.file_name }}
