name: "Create Tag"
description: "Create Tag"
inputs:
  github_ssh_private_key:
    description: "SSH private key for read/write on git repository"
    required: true
  tag:
    description: "Tag Name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.github_ssh_private_key }}

    - name: Create Tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ inputs.tag }}',
            sha: context.sha
          })
