name: "Get Git Diff Files Action"
description: "Retrieve the list of files that have changed between two specified git commit SHAs under a given path"
inputs:
  base_sha:
    description: "The base commit SHA"
    required: true
  head_sha:
    description: "The head commit SHA"
    required: true
  path:
    description: "The path to filter the diff files"
    required: true
outputs:
  diff_files:
    description: "The list of different files"
    value: ${{ steps.get_diff.outputs.diff_files }}

runs:
  using: "composite"
  steps:
    - name: Get git diff
      id: get_diff
      shell: bash
      run: |
        git fetch origin
        diff_files=$(git diff --name-only ${{ inputs.base_sha }} ${{ inputs.head_sha }} -- ${{ inputs.path }})
        echo "::set-output name=diff_files::$diff_files"
