name: On Deploy
run-name: "[On Deploy] ${{ inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Tag to deploy
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: ./.github/actions/use-node
      - name: Validate
        run: npm run validate

  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    permissions: write-all
    needs: validate
    concurrency:
      group: deploy-development
    environment: development
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Development
        uses: ./.github/actions/deploy-to-env
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          environment: development
          role_to_assume: ${{ secrets.SAM_DEPLOYMENT_ROLE_DEVELOPMENT }}

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    permissions: write-all
    needs: validate
    concurrency:
      group: deploy-uat
    environment: uat
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to UAT
        uses: ./.github/actions/deploy-to-env
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          environment: uat
          role_to_assume: ${{ secrets.SAM_DEPLOYMENT_ROLE_DEV }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions: write-all
    needs: validate
    concurrency:
      group: deploy-production
    environment: production
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Production
        uses: ./.github/actions/deploy-to-env
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          environment: production
          role_to_assume: ${{ secrets.SAM_DEPLOYMENT_ROLE_PROD }}
