name: On Push Workflow
run-name: "[On Push] ${{ github.event.head_commit.message }}"

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/use-node

      - name: Validate
        run: npm run validate

  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/use-node

      - name: Deploy to development
        uses: ./.github/actions/deploy-to-env
        with:
          environment: development
